["setup.cfg".pylint]
[MASTER]
# Add files or directories to the blacklist. They should be base names, not paths.
ignore=tests

# Pickle collected data for later comparisons.
persistent=yes

# List of plugins (as comma separated values of python modules names) to load,
# usually to register additional checkers.
load-plugins=

extension-pkg-whitelist=lxml

[MESSAGES CONTROL]

# Enable the message, report, category or checker with the given id(s). You can
# either give multiple identifier separated by comma (,) or put this option
# multiple time. See also the "--disable" option for examples.
#enable=

# C0115: Missing class docstring (missing-class-docstring)
# C0103: Constant name %r doesn't conform to UPPER_CASE naming style (invalid-name)
# C0330: Wrong hanging indentation before block (add 4 spaces)
# E0611: No name %r in module %r
# E1136: Value is unsubscriptable (unsubscriptable-object)
# E1136 is disable because it has too many false positive
# W0108: Lambda may not be necessary (unnecessary-lambda)
# E0213: Method should have "self" as first argument (no-self-argument)
# R0201: Method could be a function (no-self-use)
# R0903: Too few public methods (0/2) (too-few-public-methods)
# R0801: Similar lines in 2 files (it's bugged...)
disable=C0103, C0115, C0330, E1136, E0611, E0213, R0201, R0903, R0801, W0108

[REPORTS]

# Set the output format. Available formats are text, parseable, colorized, msvs
# (visual studio) and html. You can also give a reporter class, eg
# mypackage.mymodule.MyReporterClass.
output-format=text

# Put messages in a separate file for each module / package specified on the
# command line instead of printing them on stdout. Reports (if any) will be
# written in a file name "pylint_global.[txt|html]".
files-output=no

# Tells whether to display a full report or only the messages
#reports=yes

[FORMAT]

# Maximum number of characters on a single line.
max-line-length=120

[DESIGN]
# Maximum number of locals for function / method body
max-locals=20

# Maximum number of return / yield for function / method body
max-returns=6

# Maximum number of branch for function / method body
max-branches=12
